apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Default overlay: includes LLM inference services (llama-serve)
# Use this when deploying models directly on the cluster

namespace: rhai-agentic-demo

resources:
  - ../../base