kind: Deployment
apiVersion: apps/v1
metadata:
  name: crm
  labels:
    app: crm
    app.kubernetes.io/component: crm
    app.kubernetes.io/instance: crm
    app.kubernetes.io/name: crm
    app.kubernetes.io/part-of: crm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crm
        deployment: crm
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: crm
          image: quay.io/redhatworkshops/bgd:latest
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600