FROM registry.access.redhat.com/ubi9/nodejs-22-minimal

USER 1001

WORKDIR /opt/app-root/src/app

COPY --chown=1001:0 . .

EXPOSE 8010

CMD npx -y supergateway --stdio "node build/index.js" --port 8010
